services:
  seed:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api:/app
    working_dir: /app
    command: python -m app.seed

  backend:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=sqlite:///./faq.db
    ports:
      - "8000:8000"
    depends_on:
      - seed

  frontend:
    build:
      context: ./web-app
      target: dev
    volumes:
      - ./web-app:/app
    environment:
      - API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend